### ISSUE TITLE
Main Navigation producing incorrect HTML

### ISSUE THREAD

**Issue by raulriera** [russjohnson/SplashCMS#18]
Currently the main navigation snippet includes this

<ul class="lavaLampNoImage" id="nav">
<s:navigation urls="Home:/|Contact Us:/index.cfm/contact-us" id="nav" currentClass="active" />
</ul>

But the actual SplashTag produces an UL of it's own, so the wrapping UL in this case should be removed. Also, there closing ">" in the opening UL and the closing UL is missing in the SplashTag

**Comment by raulriera** [comment]
This is fixed in my repo

**Comment by russjohnson** [comment]
Pulled and committed.
