### ISSUE TITLE
Incorrect link the in /admin header

### ISSUE THREAD

**Issue by raulriera** [russjohnson/SplashCMS#19]
Currently the admin header points to /admin (without the use of Wheel's functions) it should link instead to the "admin_path"

**Comment by raulriera** [comment]
Solution:

Replace line 47 of views/layout.cfm with

<cfoutput>#linkTo(text=application.admin.title, route="admin_path")#</cfoutput>

**Comment by russjohnson** [comment]
Fixed and pushed to origin.
