### ISSUE TITLE
Critical pagePart error

### ISSUE THREAD

**Issue by raulriera** [russjohnson/SplashCMS#20]
Currently it seems that the pageParts are getting "scrambled" when creating/updating... content is getting duplicated, "fileName" columns are getting the same values but the "content" column is different

**Comment by raulriera** [comment]
Is it possible that 2 or more pageParts are beign "raced conditioned" by using DateTimeFormat to name them?

**Comment by raulriera** [comment]
Yup, did a quick loop test and most of the files were named the same

**Comment by raulriera** [comment]
(Uncommited fix on my repo) Add to the table column 4 chars and use CreateUUID() instead of the current UDF. If you like this solution I can apply it to the pages and snippets and commit it

**Comment by raulriera** [comment]
I fixed this on my repo, but changed the way you named the files and the length of the column... If that is cool, go ahead and pull :)

http://github.com/raulriera/SplashCMS/commit/94752a7313812db3d2fe4530e70dce8f323d3611

**Comment by russjohnson** [comment]
Pulled in and committed to Origin.
