### ISSUE TITLE
Create new layouts

### ISSUE THREAD

**Issue by raulriera** [russjohnson/SplashCMS#21]
When creating new layouts the HTML is beign parsed, so there is no "HTML". I have to edit it and paste it again and then it wont be parsed.

I dont know if you fix this on your updates, I dont know how to merge the upstream with my repo :(

**Comment by russjohnson** [comment]
Im looking at this now trying to confirm this. Are you just creating a new layout in the admin and pasting in your html?

**Comment by raulriera** [comment]
yes, pasting it from Coda (dont know if that makes a difference)

**Comment by russjohnson** [comment]
I found the problem and committed the change to Origin.
