### ISSUE TITLE
Error when browsing to any page

### ISSUE THREAD

**Issue by indynz** [russjohnson/SplashCMS#23]
I'm getting the following error when trying to view any page.

Railo 3.1.1.000 Error (Missinginclude)
Message     Page /public/layouts/09032009010255392.cfm [/Users/indy/Development/ColdFusion/jboss-5.1.0.GA/server/splashcms/deploy/railo.war/public/layouts/09032009010255392.cfm] not found
Stacktrace  The Error Occurred in
/Users/indy/Development/ColdFusion/jboss-5.1.0.GA/server/splashcms/deploy/railo.war/controllers/Viewer.cfc: line 20

```
18: <cfsavecontent variable="renderedPage">
19: <!--- include the layout --->
20: <cfinclude template="#application.defaults.rootPath#public/layouts/#request.layoutFile#">
21: </cfsavecontent>
22: <!--- <cfset renderedPage = page.process(page.slug)> --->
```

The file does not exist in the public/layout folder.

**Comment by raulriera** [comment]
Hey indy, in order to fix this you need to go through the /admin section and update all layouts, snippets and pages

**Comment by indynz** [comment]
Thanks Raul. That did it.
