### ISSUE TITLE
Where is the "ADMIN" section ?

### ISSUE THREAD

**Issue by Guba** [russjohnson/SplashCMS#24]
Hello.
I looked everywhere but I wasn't able to find any ADMIN section.
Where is it ?
Thanks

**Comment by raulriera** [comment]
yoururl.com/admin

;)

**Comment by russjohnson** [comment]
There is no physical "admin" directory. Its managed through URL rewriting and wheels routes. This was done because having controllers in subfolders in earlier releases of Wheels were a PIA.
