### ISSUE TITLE
Page Tree View seems broken

### ISSUE THREAD

**Issue by raulriera** [russjohnson/SplashCMS#25]
Although no javascript errors are thrown, the javascript tree page view is not currently working anymore

**Comment by russjohnson** [comment]
You might need to pull from the main repo again and update. Mine is working fine.

**Comment by raulriera** [comment]
Could this be related to Windows and Linux somehow? when I was on Windows it was working

**Comment by raulriera** [comment]
Yup, found the problem

http://github.com/raulriera/SplashCMS/commit/91a8182ccfe8052f5e447bc7ea04c346b5173fc2

**Comment by russjohnson** [comment]
Pulled and committed to the origin. Thanks!
