### ISSUE TITLE
Page sorting

### ISSUE THREAD

**Issue by raulriera** [russjohnson/SplashCMS#26]
(More like an "enhancement" that I want to leave here in "stone") Beign able to sort the pages in the page index view, maybe for later use of an "auto <s:navigation /> tag" or just to "pretty up" the index

**Comment by russjohnson** [comment]
This is something that I have been thinking about. Im considering doing a drag n drop sort in the page list. Not super high in priority but should start looking at it soon.

**Comment by raulriera** [comment]
I think we should switch to NestedSet plugin and add this as well http://www.swartzfager.org/blog/dspNestedList.cfm

**Comment by raulriera** [comment]
I ended up droping NestedSet and the whole page sorting idea for this 2c87dd88400279bdfc599103af436482c9491346 seems like an good fix.
