### ISSUE TITLE
Children splash tag throwing error and aborting

### ISSUE THREAD

**Issue by russjohnson** [russjohnson/SplashCMS#27]
Have been looking at this and the query in the children tag is throwing an error.

Application Exception - in /Library/WebServer/Documents/splash/lib/splash/tags/children.cfm : line 8
Attribute validation error for tag CFQUERY.

Still looking at it.

**Comment by raulriera** [comment]
really? works for me.. but only on the "layouts" on the "pages" I can't get it to continue execution of the template... maybe I shouldnt use the request scope in the page

**Comment by raulriera** [comment]
Found the problem, it was staring at the face the whole time :) you can't access caller.get('dataSourceName') from within the tag, saw your application.wheels.dataSourceName and used it... now it works like a charm. This tag of course is missing a bunch of functionality still

**Comment by russjohnson** [comment]
Pulled in your changes. Closing for now. We can add a ticket for adding any functionality to the children tag you want.
