### ISSUE TITLE
Page delete

### ISSUE THREAD

**Issue by raulriera** [russjohnson/SplashCMS#28]
When deleting a page, their children are not getting removed

**Comment by russjohnson** [comment]
Hmmm... do we want to delete the children to just move them? Deleting the child pages seems extreme for some reason. I will have to think about this for a bit.

**Comment by raulriera** [comment]
or maybe they should be set as a child to the home page.. currently they just vanish

**Comment by russjohnson** [comment]
thats kind of what Im thinking right now... should probably prompt the user if they are deleting a parent that has children and let them know the children pages will be reassigned to the home page.. or something like that...

**Comment by raulriera** [comment]
that sounds good, a quick implementation will be to add it to the flash message (but, who read those? :)

**Comment by raulriera** [comment]
Thinking about this a bit more... pages should be abled to "re parent" if this is going to be established... until the page sorting/moving can be achived
