### ISSUE TITLE
Page parts order

### ISSUE THREAD

**Issue by raulriera** [russjohnson/SplashCMS#29]
The page parts tabs are getting scrambled when creating new parts. I though they were a struct and they were randomly being sorted, but turns out they are a query, so maybe we should just order them by name?

**Comment by russjohnson** [comment]
Good idea

**Comment by raulriera** [comment]
:) http://github.com/raulriera/SplashCMS/commit/c294e0063736aa7a05dd54263e9ebed6cae6b779

**Comment by russjohnson** [comment]
Pulled and committed.
