### ISSUE TITLE
Add Username and Password to <cfquery> tags inside custom tags

### ISSUE THREAD

**Issue by cbishop** [russjohnson/SplashCMS#32]
For any <cfquery> tag inside a custom tag, add the following to support database configurations that require the username and password.
username="caller.get('dataSourceUserName')#" password="#caller.get('dataSourcePassword')#"

Right now, in the lib directory, the files that  need this are:
children.cfm
content.cfm
snippet.cfm

**Comment by cbishop** [comment]
breadcrumb.cfm also needs this code

**Comment by raulriera** [comment]
Done on children :) although I cant use caller unless on the layout so snippet and children will have to use the "direct variable" hack

**Comment by raulriera** [comment]
Fixed on my repo

**Comment by russjohnson** [comment]
Pulled into main fork.
