### ISSUE TITLE
Add a global update or a mass update function to the admin

### ISSUE THREAD

**Issue by cbishop** [russjohnson/SplashCMS#35]
If you import a lot of pages,snippets, or layouts from another database, updating all of them to get them written to the public directory is a real pain.

This is also a significant obstacle for new users. You get Splash all setup, but get a bunch of errors.

Even better than a global update, have the Viewer controller check for missing filenames and do an automatic update if needed!

<cfif NOT FileExists(application.defaults.rootPath#public/layouts/#request.layoutFile)> 
     Do the Automatic Update
</cfif>

<cfsavecontent variable="renderedPage">
    
    <cfinclude template="#application.defaults.rootPath#public/layouts/#request.layoutFile#">
</cfsavecontent>

**Comment by cbishop** [comment]
The end of this doesn't make sense because github doesn't like certain characters. The point was to check for the layout before rendering:
cfif FileExists(application.defaults.rootPath#public/layouts/#request.layoutFile)

**Comment by raulriera** [comment]
I dont know about this... if you are importing another site, why dont you bring the files as well in your public folder?

**Comment by cbishop** [comment]
Actually, that's what I thought I did. But, I still got the template not found errors, so I had to do all the updates. Or maybe something else was causing errors.

I still think this is a big problem for first-time Spash users, so there ought to be a way to avoid those file not found errors.

**Comment by russjohnson** [comment]
After looking into this, it appears that if the content is created in the db and the filename attribute doesnt exist in the db, the file still cannot be written. Im planning a fix for this now.

**Comment by cbishop** [comment]
Thanks for staying after this Russ. I think it's really going to help newbies get going smoothly.

**Comment by russjohnson** [comment]
This has been fixed and committed to the repo.
