### ISSUE TITLE
Errors on missing page, layout, and snippet files.

### ISSUE THREAD

**Issue by cbishop** [russjohnson/SplashCMS#38]
For a variety of reasons, I keep running into errors from missing pages, snippets, and layouts. This is also a problem for new users in that they have to go and update all their stuff before Splash will work.

I think what’s needed is a VerifyfIncludeExists function that runs before any cfinclude that's susceptible to an error. The function would:
• Just do nothing and return if the file exists.
• If it’s not there, lookup the key and execute the Update method in the appropriate Page, Snippet, or Layout controller.
• If it can’t find the key, or has other problems, then throw an error.

Russ mentioned the install process like Mango Blog uses. This is a good idea -- Especially automatically running the db scripts. 

But, if you fix it the way I suggested, it would automatically fix the install problem. It might be a bit slower the first time you access a new page, snippet, or layout. But, you'd just never have to worry about the problem again.

**Comment by russjohnson** [comment]
This has been added. It will now write the rendered file if it cannot be found...
