### ISSUE TITLE
Default theme

### ISSUE THREAD

**Issue by raulriera** [russjohnson/SplashCMS#41]
Should we remove all custom images and colors and just use jQuery's theme (and icons) to create the UI? There is already a bunch of jQuery UI integrated, plus that way the users could create custom themes REALLY simple.

**Comment by russjohnson** [comment]
Are you talking about the admin theme?

**Comment by raulriera** [comment]
Yeah, making it whole in jQuery UI so the themeRoller or any jQuery theme can customize the look and feel of everything
