### ISSUE TITLE
Add ability to categorize snippets

### ISSUE THREAD

**Issue by russjohnson** [russjohnson/SplashCMS#42]
After working on a site that had a good bit of content, I was really wishing I had the ability to create categories for the snippets.

Planning to add this before the next release. Still have to figure out how to implement without breaking existing sites.

**Comment by raulriera** [comment]
what do you mean? for organization or to change the behavior of the snippet? if its just for shows a tagging system will be great I guess

**Comment by russjohnson** [comment]
Mainly just for organization. The only thing affected would be the admin list when you view the snippets.

**Comment by raulriera** [comment]
http://code.drewwilson.com/entry/autosuggest-jquery-plugin :D

**Comment by russjohnson** [comment]
This feature has been added and committed. Im opening a new issue for editing and deleting the categories since that isnt in this commit.
