### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by raulriera** [russjohnson/SplashCMS#45]
I strongly tell my clients that they "write" all their content on the text editor and not "copy and paste" it from word (so they get familiar with the HTML editor) but I notice they tend to "hang" in there for long periods of time writing stuff which makes the session to time out and the  "save/update" to fail because they will be redirected to the login screen.

What would you recommend for this situations?

**Comment by russjohnson** [comment]
I would change the session timeout option for the application...I have never had to change this for a wheels site so Im not sure where most people put this...

**Comment by raulriera** [comment]
this wont overwrite the setting in the "ColdFusion Admin" right?

**Comment by russjohnson** [comment]
if you set it in the app, it will override the cfadmin setting but ONLY for that application.

**Comment by raulriera** [comment]
Thanks, you can go ahead and delete this issue then :)

**Comment by russjohnson** [comment]
no problem

**Comment by rip747** [comment]
i know this ticket is closed, but i have a suggestion. could splash implement some sort of ajax request every so often on the page so that the session stays opened?

**Comment by raulriera** [comment]
Agree with Tony...

**Comment by russjohnson** [comment]
I have actually been thinking about doing an ajax based "auto-save" which would save every so often as a "draft" of the current item being edited. Wordpress does this now and its a really nice feature. I know there are some things in place now that would help this effort but it would take some more engineering under-the-hood. Im putting this on my list. Also, if anyone is interested in contributing this feature, feel free. I already have a ton of updates to pull from Raul and put into the trunk.
