### ISSUE TITLE
Snippet categories

### ISSUE THREAD

**Issue by raulriera** [russjohnson/SplashCMS#54]
Should they be removed? with some sorting I don't see the real benefit of having categories... I can easily call my snippets "artist navigation" and "painting navigation" and so on so I can have everything next to each other... If I want to order them differently I could just sort them that way....

Thoughts?

**Comment by raulriera** [comment]
Plus, simplifies the layout

**Comment by russjohnson** [comment]
This is something that I definitely want to leave in. I have some sites that are way too big to try and manage snippets without categories. This is really optional because if you dont use categories nothing should change in the layout.

**Comment by raulriera** [comment]
I need to wrap my head around the idea on how to sort these snippets then :)

**Comment by raulriera** [comment]
How about if we rewrite that to tags? that way the system could have "tags" built in that the users can use in their extensions? This jQuery plugin is both awesome and beautiful
http://code.drewwilson.com/entry/autosuggest-jquery-plugin

**Comment by russjohnson** [comment]
Considering now just removing the snippet categories... not sure why Im chaning my mind but seriously considering removing that feature.

**Comment by raulriera** [comment]
yay :)
