### ISSUE TITLE
Layout validation

### ISSUE THREAD

**Issue by raulriera** [russjohnson/SplashCMS#56]
Should I remove the validatesPresenceOf("body")? sometimes I need blank layouts to do "dynamic" stuff in them

**Comment by russjohnson** [comment]
Yeah you could probably do that. Having a blank layout wouldnt be such a bad thing I guess..

**Comment by raulriera** [comment]
Actually this doesn't make any sense now that I implemented it on my fork, you still need to write which "page part" is going to be shown
