### ISSUE TITLE
Children-each tag should find only "published" pages

### ISSUE THREAD

**Issue by raulriera** [russjohnson/SplashCMS#59]
Also, what is the difference between "draft" and "hidden"? I would like to be able to "view" a draft for example

**Comment by russjohnson** [comment]
Draft means its not published to the site... hidden is a published page but doesnt show up in any Nav menus etc...

We really need to come up with a way to Preview draft pages... the Mark it up editor has that little preview function but it doesnt load the layouts etc.. would be cool to be able to pass a 'preview' flag in your url to allow a draft page to be viewed but only if you are logged in...

**Comment by raulriera** [comment]
I guess this is for when the navigation tag autobuilds the items right? I am going to add AND status = "published" to the getChildren function then
